apiVersion: v1
kind: Service
metadata:
 name: APP_NAME
 labels:
   app: APP_NAME
spec:
 selector:
   app: APP_NAME
 ports:
   - name: api
     protocol: TCP
     port: 80
     targetPort: 8080
 type: ClusterIP
